// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM user_roles
WHERE user_id = $1
  AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserRoles, userID)
	return err
}

const getRolesByIDs = `-- name: GetRolesByIDs :many
SELECT id, name, description, is_superuser_role, requires_provider_identifier, created_at, updated_at, tenant_id FROM roles
WHERE id::text = ANY($1::text[])
  AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
`

func (q *Queries) GetRolesByIDs(ctx context.Context, ids []string) ([]Role, error) {
	rows, err := q.db.Query(ctx, getRolesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSuperuserRole,
			&i.RequiresProviderIdentifier,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, username, email, password_hash, provider_identifier, status, failed_login_attempts, locked_until, password_changed_at, last_access_review_at, next_access_review_due, created_at, updated_at, tenant_id FROM users
WHERE id = $1
  AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProviderIdentifier,
		&i.Status,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.LastAccessReviewAt,
		&i.NextAccessReviewDue,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getUserWithRolesByID = `-- name: GetUserWithRolesByID :one
SELECT u.id, u.full_name, u.username, u.email, u.password_hash, u.provider_identifier, u.status, u.failed_login_attempts, u.locked_until, u.password_changed_at, u.last_access_review_at, u.next_access_review_due, u.created_at, u.updated_at, u.tenant_id,
    COALESCE(array_agg(DISTINCT r.name) FILTER (WHERE r.name IS NOT NULL), '{}')::text[] AS role_names,
    COALESCE(array_agg(DISTINCT p.code) FILTER (WHERE p.code IS NOT NULL), '{}')::text[] AS permission_codes,
    EXISTS (
        SELECT 1 FROM mfa_factors mf WHERE mf.user_id = u.id AND mf.confirmed_at IS NOT NULL
    ) AS mfa_enrolled
FROM users u
LEFT JOIN user_roles ur ON ur.user_id = u.id
LEFT JOIN roles r ON r.id = ur.role_id
LEFT JOIN role_permissions rp ON rp.role_id = r.id
LEFT JOIN permissions p ON p.id = rp.permission_id
WHERE u.id = $1
  AND u.tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
GROUP BY u.id
`

type GetUserWithRolesByIDRow struct {
	ID                  string             `json:"id"`
	FullName            string             `json:"full_name"`
	Username            string             `json:"username"`
	Email               string             `json:"email"`
	PasswordHash        *string            `json:"password_hash"`
	ProviderIdentifier  *string            `json:"provider_identifier"`
	Status              UserStatus         `json:"status"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
	PasswordChangedAt   pgtype.Timestamptz `json:"password_changed_at"`
	LastAccessReviewAt  pgtype.Timestamptz `json:"last_access_review_at"`
	NextAccessReviewDue pgtype.Timestamptz `json:"next_access_review_due"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TenantID            string             `json:"tenant_id"`
	RoleNames           []string           `json:"role_names"`
	PermissionCodes     []string           `json:"permission_codes"`
	MfaEnrolled         bool               `json:"mfa_enrolled"`
}

func (q *Queries) GetUserWithRolesByID(ctx context.Context, id string) (GetUserWithRolesByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserWithRolesByID, id)
	var i GetUserWithRolesByIDRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProviderIdentifier,
		&i.Status,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.LastAccessReviewAt,
		&i.NextAccessReviewDue,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
		&i.RoleNames,
		&i.PermissionCodes,
		&i.MfaEnrolled,
	)
	return i, err
}

const hasSuperuserRole = `-- name: HasSuperuserRole :one
SELECT EXISTS (
    SELECT 1 FROM user_roles ur
    JOIN roles r ON r.id = ur.role_id
    WHERE ur.user_id = $1
      AND ur.tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
      AND r.tenant_id = ur.tenant_id
      AND r.is_superuser_role = true
)
`

func (q *Queries) HasSuperuserRole(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasSuperuserRole, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertUserRole = `-- name: InsertUserRole :exec
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id
FROM users u
JOIN roles r ON r.id = $1
WHERE u.id = $2
  AND u.tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
  AND r.tenant_id = u.tenant_id
ON CONFLICT DO NOTHING
`

type InsertUserRoleParams struct {
	RoleID string `json:"role_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error {
	_, err := q.db.Exec(ctx, insertUserRole, arg.RoleID, arg.UserID)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.full_name, u.username, u.email, u.password_hash, u.provider_identifier, u.status, u.failed_login_attempts, u.locked_until, u.password_changed_at, u.last_access_review_at, u.next_access_review_due, u.created_at, u.updated_at, u.tenant_id,
    COALESCE(array_agg(DISTINCT r.name) FILTER (WHERE r.name IS NOT NULL), '{}')::text[] AS role_names,
    COALESCE(array_agg(DISTINCT p.code) FILTER (WHERE p.code IS NOT NULL), '{}')::text[] AS permission_codes,
    EXISTS (
        SELECT 1 FROM mfa_factors mf WHERE mf.user_id = u.id AND mf.confirmed_at IS NOT NULL
    ) AS mfa_enrolled
FROM users u
LEFT JOIN user_roles ur ON ur.user_id = u.id
LEFT JOIN roles r ON r.id = ur.role_id
LEFT JOIN role_permissions rp ON rp.role_id = r.id
LEFT JOIN permissions p ON p.id = rp.permission_id
WHERE u.tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
  AND ($1::text IS NULL OR EXISTS (
        SELECT 1 FROM user_roles ur2 JOIN roles r2 ON r2.id = ur2.role_id
        WHERE ur2.user_id = u.id
          AND ur2.tenant_id = u.tenant_id
          AND r2.tenant_id = u.tenant_id
          AND r2.name = $1
      ))
  AND ($2::user_status IS NULL OR u.status = $2)
  AND ($3::boolean IS NULL OR
       ($3::boolean AND (u.next_access_review_due IS NULL OR u.next_access_review_due < now())) OR
       (NOT $3::boolean AND NOT (u.next_access_review_due IS NULL OR u.next_access_review_due < now())))
GROUP BY u.id
ORDER BY u.full_name
`

type ListUsersParams struct {
	Role        *string     `json:"role"`
	Status      *UserStatus `json:"status"`
	StaleAccess *bool       `json:"stale_access"`
}

type ListUsersRow struct {
	ID                  string             `json:"id"`
	FullName            string             `json:"full_name"`
	Username            string             `json:"username"`
	Email               string             `json:"email"`
	PasswordHash        *string            `json:"password_hash"`
	ProviderIdentifier  *string            `json:"provider_identifier"`
	Status              UserStatus         `json:"status"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
	PasswordChangedAt   pgtype.Timestamptz `json:"password_changed_at"`
	LastAccessReviewAt  pgtype.Timestamptz `json:"last_access_review_at"`
	NextAccessReviewDue pgtype.Timestamptz `json:"next_access_review_due"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TenantID            string             `json:"tenant_id"`
	RoleNames           []string           `json:"role_names"`
	PermissionCodes     []string           `json:"permission_codes"`
	MfaEnrolled         bool               `json:"mfa_enrolled"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Role, arg.Status, arg.StaleAccess)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.ProviderIdentifier,
			&i.Status,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.PasswordChangedAt,
			&i.LastAccessReviewAt,
			&i.NextAccessReviewDue,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
			&i.RoleNames,
			&i.PermissionCodes,
			&i.MfaEnrolled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAccessReview = `-- name: RecordAccessReview :exec
UPDATE users SET last_access_review_at = $2, next_access_review_due = $3
WHERE id = $1
  AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
`

type RecordAccessReviewParams struct {
	ID                  string             `json:"id"`
	LastAccessReviewAt  pgtype.Timestamptz `json:"last_access_review_at"`
	NextAccessReviewDue pgtype.Timestamptz `json:"next_access_review_due"`
}

func (q *Queries) RecordAccessReview(ctx context.Context, arg RecordAccessReviewParams) error {
	_, err := q.db.Exec(ctx, recordAccessReview, arg.ID, arg.LastAccessReviewAt, arg.NextAccessReviewDue)
	return err
}

const setProviderIdentifier = `-- name: SetProviderIdentifier :exec
UPDATE users SET provider_identifier = $2
WHERE id = $1
  AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
`

type SetProviderIdentifierParams struct {
	ID                 string  `json:"id"`
	ProviderIdentifier *string `json:"provider_identifier"`
}

func (q *Queries) SetProviderIdentifier(ctx context.Context, arg SetProviderIdentifierParams) error {
	_, err := q.db.Exec(ctx, setProviderIdentifier, arg.ID, arg.ProviderIdentifier)
	return err
}

const unlockUser = `-- name: UnlockUser :exec
UPDATE users SET locked_until = NULL, failed_login_attempts = 0
WHERE id = $1
  AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
`

func (q *Queries) UnlockUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, unlockUser, id)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status = $2
WHERE id = $1
  AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
`

type UpdateUserStatusParams struct {
	ID     string     `json:"id"`
	Status UserStatus `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.Status)
	return err
}
