// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitation.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUserWithPassword = `-- name: ActivateUserWithPassword :exec
UPDATE users SET status = 'active', password_hash = $2, password_changed_at = now() WHERE id = $1
`

type ActivateUserWithPasswordParams struct {
	ID           string  `json:"id"`
	PasswordHash *string `json:"password_hash"`
}

func (q *Queries) ActivateUserWithPassword(ctx context.Context, arg ActivateUserWithPasswordParams) error {
	_, err := q.db.Exec(ctx, activateUserWithPassword, arg.ID, arg.PasswordHash)
	return err
}

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO user_roles (user_id, role_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AssignUserRoleParams struct {
	UserID string `json:"user_id"`
	RoleID string `json:"role_id"`
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole, arg.UserID, arg.RoleID)
	return err
}

const consumeInvitation = `-- name: ConsumeInvitation :exec
UPDATE invitations SET used_at = now() WHERE id = $1
`

func (q *Queries) ConsumeInvitation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, consumeInvitation, id)
	return err
}

const createEnrollmentToken = `-- name: CreateEnrollmentToken :exec
INSERT INTO enrollment_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateEnrollmentTokenParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEnrollmentToken(ctx context.Context, arg CreateEnrollmentTokenParams) error {
	_, err := q.db.Exec(ctx, createEnrollmentToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createInvitation = `-- name: CreateInvitation :exec
INSERT INTO invitations (id, user_id, invited_by, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateInvitationParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	InvitedBy string             `json:"invited_by"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) error {
	_, err := q.db.Exec(ctx, createInvitation,
		arg.ID,
		arg.UserID,
		arg.InvitedBy,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createInvitedUser = `-- name: CreateInvitedUser :one
INSERT INTO users (id, full_name, username, email, provider_identifier, status)
VALUES ($1, $2, $3, $4, $5, 'invited')
RETURNING id, full_name, username, email, password_hash, provider_identifier, status, failed_login_attempts, locked_until, password_changed_at, last_access_review_at, next_access_review_due, created_at, updated_at
`

type CreateInvitedUserParams struct {
	ID                 string  `json:"id"`
	FullName           string  `json:"full_name"`
	Username           string  `json:"username"`
	Email              string  `json:"email"`
	ProviderIdentifier *string `json:"provider_identifier"`
}

func (q *Queries) CreateInvitedUser(ctx context.Context, arg CreateInvitedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createInvitedUser,
		arg.ID,
		arg.FullName,
		arg.Username,
		arg.Email,
		arg.ProviderIdentifier,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProviderIdentifier,
		&i.Status,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.LastAccessReviewAt,
		&i.NextAccessReviewDue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, user_id, invited_by, token_hash, expires_at, used_at, created_at FROM invitations WHERE token_hash = $1
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvitedBy,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestInvitationByUserID = `-- name: GetLatestInvitationByUserID :one
SELECT id, user_id, invited_by, token_hash, expires_at, used_at, created_at FROM invitations WHERE user_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestInvitationByUserID(ctx context.Context, userID string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getLatestInvitationByUserID, userID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InvitedBy,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRolesByIDs = `-- name: GetRolesByIDs :many
SELECT id, name, description, is_superuser_role, requires_provider_identifier, created_at, updated_at FROM roles WHERE id::text = ANY($1::text[])
`

func (q *Queries) GetRolesByIDs(ctx context.Context, ids []string) ([]Role, error) {
	rows, err := q.db.Query(ctx, getRolesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSuperuserRole,
			&i.RequiresProviderIdentifier,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, username, email, password_hash, provider_identifier, status, failed_login_attempts, locked_until, password_changed_at, last_access_review_at, next_access_review_due, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProviderIdentifier,
		&i.Status,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.LastAccessReviewAt,
		&i.NextAccessReviewDue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, username, email, password_hash, provider_identifier, status, failed_login_attempts, locked_until, password_changed_at, last_access_review_at, next_access_review_due, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProviderIdentifier,
		&i.Status,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.LastAccessReviewAt,
		&i.NextAccessReviewDue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoleNames = `-- name: GetUserRoleNames :many
SELECT r.name FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.name
`

func (q *Queries) GetUserRoleNames(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoleNames, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
