// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditResult string

const (
	AuditResultSuccess AuditResult = "success"
	AuditResultFailure AuditResult = "failure"
)

func (e *AuditResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditResult(s)
	case string:
		*e = AuditResult(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditResult: %T", src)
	}
	return nil
}

type NullAuditResult struct {
	AuditResult AuditResult `json:"audit_result"`
	Valid       bool        `json:"valid"` // Valid is true if AuditResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditResult) Scan(value interface{}) error {
	if value == nil {
		ns.AuditResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditResult), nil
}

type MfaFactorType string

const (
	MfaFactorTypeTotp     MfaFactorType = "totp"
	MfaFactorTypeWebauthn MfaFactorType = "webauthn"
)

func (e *MfaFactorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MfaFactorType(s)
	case string:
		*e = MfaFactorType(s)
	default:
		return fmt.Errorf("unsupported scan type for MfaFactorType: %T", src)
	}
	return nil
}

type NullMfaFactorType struct {
	MfaFactorType MfaFactorType `json:"mfa_factor_type"`
	Valid         bool          `json:"valid"` // Valid is true if MfaFactorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMfaFactorType) Scan(value interface{}) error {
	if value == nil {
		ns.MfaFactorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MfaFactorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMfaFactorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MfaFactorType), nil
}

type OrganizationStatus string

const (
	OrganizationStatusPending   OrganizationStatus = "pending"
	OrganizationStatusActive    OrganizationStatus = "active"
	OrganizationStatusSuspended OrganizationStatus = "suspended"
)

func (e *OrganizationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrganizationStatus(s)
	case string:
		*e = OrganizationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrganizationStatus: %T", src)
	}
	return nil
}

type NullOrganizationStatus struct {
	OrganizationStatus OrganizationStatus `json:"organization_status"`
	Valid              bool               `json:"valid"` // Valid is true if OrganizationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrganizationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrganizationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrganizationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrganizationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrganizationStatus), nil
}

type PatientCorrectionStatus string

const (
	PatientCorrectionStatusPending  PatientCorrectionStatus = "pending"
	PatientCorrectionStatusActioned PatientCorrectionStatus = "actioned"
	PatientCorrectionStatusRejected PatientCorrectionStatus = "rejected"
)

func (e *PatientCorrectionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PatientCorrectionStatus(s)
	case string:
		*e = PatientCorrectionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PatientCorrectionStatus: %T", src)
	}
	return nil
}

type NullPatientCorrectionStatus struct {
	PatientCorrectionStatus PatientCorrectionStatus `json:"patient_correction_status"`
	Valid                   bool                    `json:"valid"` // Valid is true if PatientCorrectionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPatientCorrectionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PatientCorrectionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PatientCorrectionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPatientCorrectionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PatientCorrectionStatus), nil
}

type PatientGender string

const (
	PatientGenderMale    PatientGender = "male"
	PatientGenderFemale  PatientGender = "female"
	PatientGenderUnknown PatientGender = "unknown"
)

func (e *PatientGender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PatientGender(s)
	case string:
		*e = PatientGender(s)
	default:
		return fmt.Errorf("unsupported scan type for PatientGender: %T", src)
	}
	return nil
}

type NullPatientGender struct {
	PatientGender PatientGender `json:"patient_gender"`
	Valid         bool          `json:"valid"` // Valid is true if PatientGender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPatientGender) Scan(value interface{}) error {
	if value == nil {
		ns.PatientGender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PatientGender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPatientGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PatientGender), nil
}

type PatientStatus string

const (
	PatientStatusActive   PatientStatus = "active"
	PatientStatusDeceased PatientStatus = "deceased"
	PatientStatusMerged   PatientStatus = "merged"
)

func (e *PatientStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PatientStatus(s)
	case string:
		*e = PatientStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PatientStatus: %T", src)
	}
	return nil
}

type NullPatientStatus struct {
	PatientStatus PatientStatus `json:"patient_status"`
	Valid         bool          `json:"valid"` // Valid is true if PatientStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPatientStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PatientStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PatientStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPatientStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PatientStatus), nil
}

type UserStatus string

const (
	UserStatusInvited       UserStatus = "invited"
	UserStatusActive        UserStatus = "active"
	UserStatusSuspended     UserStatus = "suspended"
	UserStatusPendingReview UserStatus = "pending_review"
	UserStatusDeactivated   UserStatus = "deactivated"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type WebauthnCeremonyPurpose string

const (
	WebauthnCeremonyPurposeRegistration   WebauthnCeremonyPurpose = "registration"
	WebauthnCeremonyPurposeAuthentication WebauthnCeremonyPurpose = "authentication"
)

func (e *WebauthnCeremonyPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebauthnCeremonyPurpose(s)
	case string:
		*e = WebauthnCeremonyPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for WebauthnCeremonyPurpose: %T", src)
	}
	return nil
}

type NullWebauthnCeremonyPurpose struct {
	WebauthnCeremonyPurpose WebauthnCeremonyPurpose `json:"webauthn_ceremony_purpose"`
	Valid                   bool                    `json:"valid"` // Valid is true if WebauthnCeremonyPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebauthnCeremonyPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.WebauthnCeremonyPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebauthnCeremonyPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebauthnCeremonyPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebauthnCeremonyPurpose), nil
}

type AuditLog struct {
	ID             string             `json:"id"`
	Timestamp      pgtype.Timestamptz `json:"timestamp"`
	UserID         *string            `json:"user_id"`
	Action         string             `json:"action"`
	TargetResource string             `json:"target_resource"`
	IpAddress      string             `json:"ip_address"`
	Result         AuditResult        `json:"result"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	TenantID       string             `json:"tenant_id"`
}

type EnrollmentToken struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TenantID   string             `json:"tenant_id"`
}

type Invitation struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	InvitedBy string             `json:"invited_by"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TenantID  string             `json:"tenant_id"`
}

type LoginChallenge struct {
	ID                 string             `json:"id"`
	UserID             string             `json:"user_id"`
	ChallengeTokenHash string             `json:"challenge_token_hash"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt         pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	TenantID           string             `json:"tenant_id"`
}

type MfaBackupCode struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TenantID  string             `json:"tenant_id"`
}

type MfaFactor struct {
	ID              string             `json:"id"`
	UserID          string             `json:"user_id"`
	Type            MfaFactorType      `json:"type"`
	Label           string             `json:"label"`
	SecretEncrypted *string            `json:"secret_encrypted"`
	PublicKey       *string            `json:"public_key"`
	ConfirmedAt     pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	TenantID        string             `json:"tenant_id"`
}

type MfaResetToken struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	UserID      string             `json:"user_id"`
	RequestedBy string             `json:"requested_by"`
	TokenHash   string             `json:"token_hash"`
	Reason      string             `json:"reason"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID               string             `json:"id"`
	OrganizationName string             `json:"organization_name"`
	Slug             string             `json:"slug"`
	Status           OrganizationStatus `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationActivationToken struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PasswordResetAttempt struct {
	ID                string             `json:"id"`
	UsernameAttempted string             `json:"username_attempted"`
	IpAddress         string             `json:"ip_address"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	TenantID          string             `json:"tenant_id"`
}

type PasswordResetToken struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TenantID  string             `json:"tenant_id"`
}

type Patient struct {
	ID             string             `json:"id"`
	TenantID       string             `json:"tenant_id"`
	Mrn            string             `json:"mrn"`
	FullName       string             `json:"full_name"`
	Dob            pgtype.Date        `json:"dob"`
	DobEstimated   bool               `json:"dob_estimated"`
	ApproxAgeYears *int16             `json:"approx_age_years"`
	Gender         PatientGender      `json:"gender"`
	Phone          *string            `json:"phone"`
	Address        *string            `json:"address"`
	NationalID     *string            `json:"national_id"`
	Status         PatientStatus      `json:"status"`
	DateOfDeath    pgtype.Timestamptz `json:"date_of_death"`
	Insured        bool               `json:"insured"`
	GuardianID     *string            `json:"guardian_id"`
	MergedIntoID   *string            `json:"merged_into_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PatientActivityLog struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	PatientID string             `json:"patient_id"`
	UserID    *string            `json:"user_id"`
	Kind      string             `json:"kind"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PatientConsent struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	PatientID string             `json:"patient_id"`
	Scope     string             `json:"scope"`
	Granted   bool               `json:"granted"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PatientCorrection struct {
	ID             string                  `json:"id"`
	TenantID       string                  `json:"tenant_id"`
	PatientID      string                  `json:"patient_id"`
	Field          string                  `json:"field"`
	CurrentValue   *string                 `json:"current_value"`
	RequestedValue string                  `json:"requested_value"`
	EvidenceNote   *string                 `json:"evidence_note"`
	Status         PatientCorrectionStatus `json:"status"`
	SubmittedBy    *string                 `json:"submitted_by"`
	DecidedBy      *string                 `json:"decided_by"`
	DecidedAt      pgtype.Timestamptz      `json:"decided_at"`
	DecisionNote   *string                 `json:"decision_note"`
	CreatedAt      pgtype.Timestamptz      `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz      `json:"updated_at"`
}

type PatientIdentifier struct {
	ID         string             `json:"id"`
	TenantID   string             `json:"tenant_id"`
	PatientID  string             `json:"patient_id"`
	IDType     string             `json:"id_type"`
	IDValue    string             `json:"id_value"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type PatientMrnSequence struct {
	TenantID  string `json:"tenant_id"`
	NextValue int64  `json:"next_value"`
}

type Permission struct {
	ID          string `json:"id"`
	Code        string `json:"code"`
	Description string `json:"description"`
}

type ReactivationToken struct {
	ID          string             `json:"id"`
	TenantID    string             `json:"tenant_id"`
	UserID      string             `json:"user_id"`
	RequestedBy string             `json:"requested_by"`
	TokenHash   string             `json:"token_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UsedAt      pgtype.Timestamptz `json:"used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        string             `json:"id"`
	SessionID string             `json:"session_id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TenantID  string             `json:"tenant_id"`
}

type Role struct {
	ID                         string             `json:"id"`
	Name                       string             `json:"name"`
	Description                string             `json:"description"`
	IsSuperuserRole            bool               `json:"is_superuser_role"`
	RequiresProviderIdentifier bool               `json:"requires_provider_identifier"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	TenantID                   string             `json:"tenant_id"`
}

type RolePermission struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
	TenantID     string `json:"tenant_id"`
}

type Session struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	DeviceLabel  string             `json:"device_label"`
	IpAddress    string             `json:"ip_address"`
	UserAgent    string             `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	TenantID     string             `json:"tenant_id"`
	RememberMe   bool               `json:"remember_me"`
}

type User struct {
	ID                  string             `json:"id"`
	FullName            string             `json:"full_name"`
	Username            string             `json:"username"`
	Email               string             `json:"email"`
	PasswordHash        *string            `json:"password_hash"`
	ProviderIdentifier  *string            `json:"provider_identifier"`
	Status              UserStatus         `json:"status"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
	PasswordChangedAt   pgtype.Timestamptz `json:"password_changed_at"`
	LastAccessReviewAt  pgtype.Timestamptz `json:"last_access_review_at"`
	NextAccessReviewDue pgtype.Timestamptz `json:"next_access_review_due"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TenantID            string             `json:"tenant_id"`
	DeactivatedAt       pgtype.Timestamptz `json:"deactivated_at"`
}

type UserRole struct {
	UserID     string             `json:"user_id"`
	RoleID     string             `json:"role_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	TenantID   string             `json:"tenant_id"`
}

type WebauthnCeremony struct {
	ID                string                  `json:"id"`
	TenantID          string                  `json:"tenant_id"`
	UserID            string                  `json:"user_id"`
	LoginChallengeID  *string                 `json:"login_challenge_id"`
	EnrollmentTokenID *string                 `json:"enrollment_token_id"`
	Purpose           WebauthnCeremonyPurpose `json:"purpose"`
	Label             string                  `json:"label"`
	SessionData       []byte                  `json:"session_data"`
	ExpiresAt         pgtype.Timestamptz      `json:"expires_at"`
	ConsumedAt        pgtype.Timestamptz      `json:"consumed_at"`
	CreatedAt         pgtype.Timestamptz      `json:"created_at"`
}

type WebauthnCredential struct {
	ID           string             `json:"id"`
	TenantID     string             `json:"tenant_id"`
	UserID       string             `json:"user_id"`
	FactorID     string             `json:"factor_id"`
	CredentialID []byte             `json:"credential_id"`
	Credential   []byte             `json:"credential"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
