// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeLoginChallenge = `-- name: ConsumeLoginChallenge :exec
UPDATE login_challenges
SET consumed_at = now()
WHERE id = $1
`

func (q *Queries) ConsumeLoginChallenge(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, consumeLoginChallenge, id)
	return err
}

const createLoginChallenge = `-- name: CreateLoginChallenge :exec
INSERT INTO login_challenges (id, user_id, challenge_token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateLoginChallengeParams struct {
	ID                 string             `json:"id"`
	UserID             string             `json:"user_id"`
	ChallengeTokenHash string             `json:"challenge_token_hash"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateLoginChallenge(ctx context.Context, arg CreateLoginChallengeParams) error {
	_, err := q.db.Exec(ctx, createLoginChallenge,
		arg.ID,
		arg.UserID,
		arg.ChallengeTokenHash,
		arg.ExpiresAt,
	)
	return err
}

const getLoginChallengeByHash = `-- name: GetLoginChallengeByHash :one
SELECT id, user_id, challenge_token_hash, expires_at, consumed_at, created_at FROM login_challenges WHERE challenge_token_hash = $1
`

func (q *Queries) GetLoginChallengeByHash(ctx context.Context, challengeTokenHash string) (LoginChallenge, error) {
	row := q.db.QueryRow(ctx, getLoginChallengeByHash, challengeTokenHash)
	var i LoginChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeTokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, username, email, password_hash, provider_identifier, status, failed_login_attempts, locked_until, password_changed_at, last_access_review_at, next_access_review_due, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProviderIdentifier,
		&i.Status,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.LastAccessReviewAt,
		&i.NextAccessReviewDue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, full_name, username, email, password_hash, provider_identifier, status, failed_login_attempts, locked_until, password_changed_at, last_access_review_at, next_access_review_due, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.ProviderIdentifier,
		&i.Status,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.LastAccessReviewAt,
		&i.NextAccessReviewDue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementFailedLoginAttempts = `-- name: IncrementFailedLoginAttempts :one
UPDATE users
SET failed_login_attempts = failed_login_attempts + 1
WHERE id = $1
RETURNING failed_login_attempts
`

func (q *Queries) IncrementFailedLoginAttempts(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, incrementFailedLoginAttempts, id)
	var failed_login_attempts int32
	err := row.Scan(&failed_login_attempts)
	return failed_login_attempts, err
}

const lockUser = `-- name: LockUser :exec
UPDATE users
SET locked_until = $2
WHERE id = $1
`

type LockUserParams struct {
	ID          string             `json:"id"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) error {
	_, err := q.db.Exec(ctx, lockUser, arg.ID, arg.LockedUntil)
	return err
}

const resetFailedLoginAttempts = `-- name: ResetFailedLoginAttempts :exec
UPDATE users
SET failed_login_attempts = 0
WHERE id = $1
`

func (q *Queries) ResetFailedLoginAttempts(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, resetFailedLoginAttempts, id)
	return err
}

const unlockUser = `-- name: UnlockUser :exec
UPDATE users
SET locked_until = NULL, failed_login_attempts = 0
WHERE id = $1
`

func (q *Queries) UnlockUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, unlockUser, id)
	return err
}
