// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfa.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmMFAFactor = `-- name: ConfirmMFAFactor :exec
UPDATE mfa_factors SET confirmed_at = now() WHERE id = $1
`

func (q *Queries) ConfirmMFAFactor(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, confirmMFAFactor, id)
	return err
}

const consumeEnrollmentToken = `-- name: ConsumeEnrollmentToken :exec
UPDATE enrollment_tokens SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumeEnrollmentToken(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, consumeEnrollmentToken, id)
	return err
}

const consumeMFABackupCode = `-- name: ConsumeMFABackupCode :exec
UPDATE mfa_backup_codes SET used_at = now() WHERE id = $1
`

func (q *Queries) ConsumeMFABackupCode(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, consumeMFABackupCode, id)
	return err
}

const countConfirmedMFAFactors = `-- name: CountConfirmedMFAFactors :one
SELECT count(*) FROM mfa_factors WHERE user_id = $1 AND confirmed_at IS NOT NULL
`

func (q *Queries) CountConfirmedMFAFactors(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countConfirmedMFAFactors, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMFABackupCode = `-- name: CreateMFABackupCode :exec
INSERT INTO mfa_backup_codes (id, user_id, code_hash)
VALUES ($1, $2, $3)
`

type CreateMFABackupCodeParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	CodeHash string `json:"code_hash"`
}

func (q *Queries) CreateMFABackupCode(ctx context.Context, arg CreateMFABackupCodeParams) error {
	_, err := q.db.Exec(ctx, createMFABackupCode, arg.ID, arg.UserID, arg.CodeHash)
	return err
}

const createMFAFactor = `-- name: CreateMFAFactor :one
INSERT INTO mfa_factors (id, user_id, type, label, secret_encrypted, public_key, confirmed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, type, label, secret_encrypted, public_key, confirmed_at, created_at, tenant_id
`

type CreateMFAFactorParams struct {
	ID              string             `json:"id"`
	UserID          string             `json:"user_id"`
	Type            MfaFactorType      `json:"type"`
	Label           string             `json:"label"`
	SecretEncrypted *string            `json:"secret_encrypted"`
	PublicKey       *string            `json:"public_key"`
	ConfirmedAt     pgtype.Timestamptz `json:"confirmed_at"`
}

func (q *Queries) CreateMFAFactor(ctx context.Context, arg CreateMFAFactorParams) (MfaFactor, error) {
	row := q.db.QueryRow(ctx, createMFAFactor,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Label,
		arg.SecretEncrypted,
		arg.PublicKey,
		arg.ConfirmedAt,
	)
	var i MfaFactor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Label,
		&i.SecretEncrypted,
		&i.PublicKey,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const deleteMFAFactor = `-- name: DeleteMFAFactor :exec
DELETE FROM mfa_factors WHERE id = $1
`

func (q *Queries) DeleteMFAFactor(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMFAFactor, id)
	return err
}

const getEnrollmentTokenByHash = `-- name: GetEnrollmentTokenByHash :one
SELECT id::text, user_id::text, expires_at,
       CASE WHEN consumed_at IS NULL THEN false ELSE true END::boolean AS consumed
FROM enrollment_tokens
WHERE token_hash = $1
`

type GetEnrollmentTokenByHashRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Consumed  bool               `json:"consumed"`
}

func (q *Queries) GetEnrollmentTokenByHash(ctx context.Context, tokenHash string) (GetEnrollmentTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getEnrollmentTokenByHash, tokenHash)
	var i GetEnrollmentTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Consumed,
	)
	return i, err
}

const getMFAFactorByID = `-- name: GetMFAFactorByID :one
SELECT id, user_id, type, label, secret_encrypted, public_key, confirmed_at, created_at, tenant_id FROM mfa_factors WHERE id = $1
`

func (q *Queries) GetMFAFactorByID(ctx context.Context, id string) (MfaFactor, error) {
	row := q.db.QueryRow(ctx, getMFAFactorByID, id)
	var i MfaFactor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Label,
		&i.SecretEncrypted,
		&i.PublicKey,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const getUnusedMFABackupCodeByHash = `-- name: GetUnusedMFABackupCodeByHash :one
SELECT id, user_id, code_hash, used_at, created_at, tenant_id FROM mfa_backup_codes WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
`

type GetUnusedMFABackupCodeByHashParams struct {
	UserID   string `json:"user_id"`
	CodeHash string `json:"code_hash"`
}

func (q *Queries) GetUnusedMFABackupCodeByHash(ctx context.Context, arg GetUnusedMFABackupCodeByHashParams) (MfaBackupCode, error) {
	row := q.db.QueryRow(ctx, getUnusedMFABackupCodeByHash, arg.UserID, arg.CodeHash)
	var i MfaBackupCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.UsedAt,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const listMFAFactorsByUser = `-- name: ListMFAFactorsByUser :many
SELECT id, user_id, type, label, secret_encrypted, public_key, confirmed_at, created_at, tenant_id FROM mfa_factors WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListMFAFactorsByUser(ctx context.Context, userID string) ([]MfaFactor, error) {
	rows, err := q.db.Query(ctx, listMFAFactorsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MfaFactor
	for rows.Next() {
		var i MfaFactor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Label,
			&i.SecretEncrypted,
			&i.PublicKey,
			&i.ConfirmedAt,
			&i.CreatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
