// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passwords.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :exec
UPDATE password_reset_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, consumePasswordResetToken, id)
	return err
}

const countPasswordResetAttemptsByIP = `-- name: CountPasswordResetAttemptsByIP :one
SELECT count(*) FROM password_reset_attempts
WHERE ip_address = $1 AND created_at > $2
`

type CountPasswordResetAttemptsByIPParams struct {
	IpAddress string             `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountPasswordResetAttemptsByIP(ctx context.Context, arg CountPasswordResetAttemptsByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPasswordResetAttemptsByIP, arg.IpAddress, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPasswordResetAttemptsByUsername = `-- name: CountPasswordResetAttemptsByUsername :one
SELECT count(*) FROM password_reset_attempts
WHERE username_attempted = $1 AND created_at > $2
`

type CountPasswordResetAttemptsByUsernameParams struct {
	UsernameAttempted string             `json:"username_attempted"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountPasswordResetAttemptsByUsername(ctx context.Context, arg CountPasswordResetAttemptsByUsernameParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPasswordResetAttemptsByUsername, arg.UsernameAttempted, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreatePasswordResetTokenParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at FROM password_reset_tokens WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateOtherPasswordResetTokens = `-- name: InvalidateOtherPasswordResetTokens :exec
UPDATE password_reset_tokens
SET used_at = now()
WHERE user_id = $1 AND id != $2 AND used_at IS NULL
`

type InvalidateOtherPasswordResetTokensParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

func (q *Queries) InvalidateOtherPasswordResetTokens(ctx context.Context, arg InvalidateOtherPasswordResetTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateOtherPasswordResetTokens, arg.UserID, arg.ID)
	return err
}

const recordPasswordResetAttempt = `-- name: RecordPasswordResetAttempt :exec
INSERT INTO password_reset_attempts (id, username_attempted, ip_address)
VALUES ($1, $2, $3)
`

type RecordPasswordResetAttemptParams struct {
	ID                string `json:"id"`
	UsernameAttempted string `json:"username_attempted"`
	IpAddress         string `json:"ip_address"`
}

func (q *Queries) RecordPasswordResetAttempt(ctx context.Context, arg RecordPasswordResetAttemptParams) error {
	_, err := q.db.Exec(ctx, recordPasswordResetAttempt, arg.ID, arg.UsernameAttempted, arg.IpAddress)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $2, password_changed_at = now() WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           string  `json:"id"`
	PasswordHash *string `json:"password_hash"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}
