// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passwords.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeRecoveryMFA = `-- name: CompleteRecoveryMFA :execrows
UPDATE recovery_sessions SET mfa_completed_at = now(), consumed_at = CASE WHEN NOT can_reset_password OR password_completed_at IS NOT NULL THEN now() ELSE consumed_at END
WHERE id = $1 AND mfa_completed_at IS NULL AND consumed_at IS NULL
`

func (q *Queries) CompleteRecoveryMFA(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, completeRecoveryMFA, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeRecoveryPassword = `-- name: CompleteRecoveryPassword :execrows
UPDATE recovery_sessions SET password_completed_at = now(), consumed_at = CASE WHEN NOT can_replace_mfa OR mfa_completed_at IS NOT NULL THEN now() ELSE consumed_at END
WHERE id = $1 AND password_completed_at IS NULL AND consumed_at IS NULL
`

func (q *Queries) CompleteRecoveryPassword(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, completeRecoveryPassword, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :exec
UPDATE password_reset_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, consumePasswordResetToken, id)
	return err
}

const consumeRecoveryEmailToken = `-- name: ConsumeRecoveryEmailToken :one
UPDATE recovery_email_tokens SET consumed_at = now()
WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > now() RETURNING id, tenant_id, user_id, intent, token_hash, expires_at, consumed_at, created_at
`

func (q *Queries) ConsumeRecoveryEmailToken(ctx context.Context, tokenHash string) (RecoveryEmailToken, error) {
	row := q.db.QueryRow(ctx, consumeRecoveryEmailToken, tokenHash)
	var i RecoveryEmailToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Intent,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countPasswordResetAttemptsByIP = `-- name: CountPasswordResetAttemptsByIP :one
SELECT count(*) FROM password_reset_attempts
WHERE ip_address = $1 AND created_at > $2
`

type CountPasswordResetAttemptsByIPParams struct {
	IpAddress string             `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountPasswordResetAttemptsByIP(ctx context.Context, arg CountPasswordResetAttemptsByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPasswordResetAttemptsByIP, arg.IpAddress, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPasswordResetAttemptsByUsername = `-- name: CountPasswordResetAttemptsByUsername :one
SELECT count(*) FROM password_reset_attempts
WHERE username_attempted = $1 AND created_at > $2
`

type CountPasswordResetAttemptsByUsernameParams struct {
	UsernameAttempted string             `json:"username_attempted"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountPasswordResetAttemptsByUsername(ctx context.Context, arg CountPasswordResetAttemptsByUsernameParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPasswordResetAttemptsByUsername, arg.UsernameAttempted, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreatePasswordResetTokenParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createRecoveryEmailToken = `-- name: CreateRecoveryEmailToken :exec
INSERT INTO recovery_email_tokens (id, user_id, intent, token_hash, expires_at) VALUES ($1, $2, $3, $4, $5)
`

type CreateRecoveryEmailTokenParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Intent    RecoveryIntent     `json:"intent"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRecoveryEmailToken(ctx context.Context, arg CreateRecoveryEmailTokenParams) error {
	_, err := q.db.Exec(ctx, createRecoveryEmailToken,
		arg.ID,
		arg.UserID,
		arg.Intent,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createRecoverySession = `-- name: CreateRecoverySession :exec
INSERT INTO recovery_sessions (id, user_id, token_hash, can_reset_password, can_replace_mfa, expires_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateRecoverySessionParams struct {
	ID               string             `json:"id"`
	UserID           string             `json:"user_id"`
	TokenHash        string             `json:"token_hash"`
	CanResetPassword bool               `json:"can_reset_password"`
	CanReplaceMfa    bool               `json:"can_replace_mfa"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRecoverySession(ctx context.Context, arg CreateRecoverySessionParams) error {
	_, err := q.db.Exec(ctx, createRecoverySession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CanResetPassword,
		arg.CanReplaceMfa,
		arg.ExpiresAt,
	)
	return err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at, tenant_id FROM password_reset_tokens WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const getRecoverySessionByHash = `-- name: GetRecoverySessionByHash :one
SELECT id, tenant_id, user_id, token_hash, can_reset_password, can_replace_mfa, password_completed_at, mfa_completed_at, failed_attempts, expires_at, consumed_at, created_at FROM recovery_sessions WHERE token_hash = $1
`

func (q *Queries) GetRecoverySessionByHash(ctx context.Context, tokenHash string) (RecoverySession, error) {
	row := q.db.QueryRow(ctx, getRecoverySessionByHash, tokenHash)
	var i RecoverySession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.CanResetPassword,
		&i.CanReplaceMfa,
		&i.PasswordCompletedAt,
		&i.MfaCompletedAt,
		&i.FailedAttempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementRecoverySessionFailure = `-- name: IncrementRecoverySessionFailure :one
UPDATE recovery_sessions SET failed_attempts = failed_attempts + 1 WHERE id = $1 RETURNING failed_attempts
`

func (q *Queries) IncrementRecoverySessionFailure(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, incrementRecoverySessionFailure, id)
	var failed_attempts int32
	err := row.Scan(&failed_attempts)
	return failed_attempts, err
}

const invalidateOtherPasswordResetTokens = `-- name: InvalidateOtherPasswordResetTokens :exec
UPDATE password_reset_tokens
SET used_at = now()
WHERE user_id = $1 AND id != $2 AND used_at IS NULL
`

type InvalidateOtherPasswordResetTokensParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

func (q *Queries) InvalidateOtherPasswordResetTokens(ctx context.Context, arg InvalidateOtherPasswordResetTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateOtherPasswordResetTokens, arg.UserID, arg.ID)
	return err
}

const invalidateRecoveryEmailTokens = `-- name: InvalidateRecoveryEmailTokens :exec
UPDATE recovery_email_tokens SET consumed_at = now() WHERE user_id = $1 AND intent = $2 AND consumed_at IS NULL
`

type InvalidateRecoveryEmailTokensParams struct {
	UserID string         `json:"user_id"`
	Intent RecoveryIntent `json:"intent"`
}

func (q *Queries) InvalidateRecoveryEmailTokens(ctx context.Context, arg InvalidateRecoveryEmailTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateRecoveryEmailTokens, arg.UserID, arg.Intent)
	return err
}

const invalidateRecoverySessionsByUser = `-- name: InvalidateRecoverySessionsByUser :exec
UPDATE recovery_sessions SET consumed_at = now() WHERE user_id = $1 AND consumed_at IS NULL AND id != $2
`

type InvalidateRecoverySessionsByUserParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

func (q *Queries) InvalidateRecoverySessionsByUser(ctx context.Context, arg InvalidateRecoverySessionsByUserParams) error {
	_, err := q.db.Exec(ctx, invalidateRecoverySessionsByUser, arg.UserID, arg.ID)
	return err
}

const recordPasswordResetAttempt = `-- name: RecordPasswordResetAttempt :exec
INSERT INTO password_reset_attempts (id, username_attempted, ip_address)
VALUES ($1, $2, $3)
`

type RecordPasswordResetAttemptParams struct {
	ID                string `json:"id"`
	UsernameAttempted string `json:"username_attempted"`
	IpAddress         string `json:"ip_address"`
}

func (q *Queries) RecordPasswordResetAttempt(ctx context.Context, arg RecordPasswordResetAttemptParams) error {
	_, err := q.db.Exec(ctx, recordPasswordResetAttempt, arg.ID, arg.UsernameAttempted, arg.IpAddress)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $2, password_changed_at = now() WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           string  `json:"id"`
	PasswordHash *string `json:"password_hash"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}
