// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, session_id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRefreshTokenParams struct {
	ID        string             `json:"id"`
	SessionID string             `json:"session_id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.SessionID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, session_id, user_id, token_hash, expires_at, revoked_at, created_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeRefreshTokensBySession = `-- name: RevokeRefreshTokensBySession :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE session_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokensBySession(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensBySession, sessionID)
	return err
}

const revokeRefreshTokensByUser = `-- name: RevokeRefreshTokensByUser :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokensByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensByUser, userID)
	return err
}

const revokeRefreshTokensByUserExceptSession = `-- name: RevokeRefreshTokensByUserExceptSession :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE user_id = $1 AND session_id != $2 AND revoked_at IS NULL
`

type RevokeRefreshTokensByUserExceptSessionParams struct {
	UserID    string `json:"user_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) RevokeRefreshTokensByUserExceptSession(ctx context.Context, arg RevokeRefreshTokensByUserExceptSessionParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensByUserExceptSession, arg.UserID, arg.SessionID)
	return err
}
