// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, device_label, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	DeviceLabel string `json:"device_label"`
	IpAddress   string `json:"ip_address"`
	UserAgent   string `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.DeviceLabel,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, device_label, ip_address, user_agent, created_at, last_active_at, revoked_at, tenant_id FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceLabel,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.RevokedAt,
		&i.TenantID,
	)
	return i, err
}

const listActiveSessionsByUser = `-- name: ListActiveSessionsByUser :many
SELECT id, user_id, device_label, ip_address, user_agent, created_at, last_active_at, revoked_at, tenant_id FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY last_active_at DESC
`

func (q *Queries) ListActiveSessionsByUser(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceLabel,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastActiveAt,
			&i.RevokedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionsByUser = `-- name: RevokeSessionsByUser :exec
UPDATE sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionsByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeSessionsByUser, userID)
	return err
}

const revokeSessionsByUserExceptSession = `-- name: RevokeSessionsByUserExceptSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1 AND id != $2 AND revoked_at IS NULL
`

type RevokeSessionsByUserExceptSessionParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

func (q *Queries) RevokeSessionsByUserExceptSession(ctx context.Context, arg RevokeSessionsByUserExceptSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSessionsByUserExceptSession, arg.UserID, arg.ID)
	return err
}

const touchSessionLastActive = `-- name: TouchSessionLastActive :exec
UPDATE sessions SET last_active_at = now() WHERE id = $1
`

func (q *Queries) TouchSessionLastActive(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchSessionLastActive, id)
	return err
}
