package clinical

import "context"

type Repository interface {
	ListTemplates(context.Context, string, string) ([]ClinicalTemplate, error)
	GetTemplate(context.Context, string) (*ClinicalTemplate, error)
	CreateTemplate(context.Context, ClinicalTemplate, ClinicalTemplateVersion) (*ClinicalTemplate, error)
	CreateTemplateDraft(context.Context, string, string, string) (*ClinicalTemplate, error)
	UpdateTemplateDraft(context.Context, string, string, UpdateTemplateDraftRequest) (*ClinicalTemplate, error)
	PublishTemplate(context.Context, string, string) (*ClinicalTemplate, error)
	SetDefaultTemplate(context.Context, string) (*ClinicalTemplate, error)
	ArchiveTemplate(context.Context, string) (*ClinicalTemplate, error)
	CreateEncounterForm(context.Context, string, string, string) (*EncounterForm, error)
	GetEncounterForm(context.Context, string) (*EncounterForm, error)
	ListEncounterForms(context.Context, string) ([]EncounterForm, error)
	SaveEncounterForm(context.Context, string, string, SaveEncounterFormRequest) (*EncounterForm, error)
	SubmitEncounterForm(context.Context, EncounterForm, string, []Observation) (*EncounterForm, error)
	ListCatalogueServices(context.Context, CatalogueFilters) ([]CatalogueService, int, error)
	CreateCatalogueService(context.Context, CatalogueService) (*CatalogueService, error)
	UpdateCatalogueService(context.Context, string, CatalogueService) (*CatalogueService, error)
	SetCatalogueServiceActive(context.Context, string, bool) (*CatalogueService, error)
	ListMedicationCatalogue(context.Context, CatalogueFilters) ([]MedicationDefinition, int, error)
	CreateMedicationDefinition(context.Context, MedicationDefinition) (*MedicationDefinition, error)
	UpdateMedicationDefinition(context.Context, string, MedicationDefinition) (*MedicationDefinition, error)
	SetMedicationDefinitionActive(context.Context, string, bool) (*MedicationDefinition, error)
	ListCatalogueReferences(context.Context, string, CatalogueFilters) ([]CatalogueReferenceItem, int, error)
	AdoptServiceReferences(context.Context, []CatalogueService) ([]CatalogueService, error)
	AdoptMedicationReferences(context.Context, []MedicationDefinition) ([]MedicationDefinition, error)
	CatalogueCodes(context.Context, string, []string) (map[string]bool, error)
	VocabularyCodes(context.Context, string) (map[string]string, error)
	ResolveDepartmentCodes(context.Context, []string) (map[string]string, error)
	ResolveServicePointCodes(context.Context, []string) (map[string]ServicePointImportReference, error)
	ResolveCatalogueReferenceCodes(context.Context, string, []string) (map[string]string, error)
	SaveCatalogueImport(context.Context, CatalogueImport, string) error
	GetCatalogueImport(context.Context, string) (*CatalogueImport, error)
	CommitCatalogueImport(context.Context, CatalogueImport, []CatalogueService, []MedicationDefinition) error
	ListResources(context.Context, string) ([]Resource, error)
	CreateResource(context.Context, string, Resource) (*Resource, error)
	UpdateResource(context.Context, string, string, UpdateResourceRequest) (*Resource, error)
	DeactivationImpact(context.Context, string, string) (*DeactivationImpact, error)
	DeactivateResource(context.Context, string, string, bool) (*ResourceLifecycleResult, error)
	ReactivateResource(context.Context, string, string) (*Resource, error)
	CreateVisit(context.Context, Visit) (*Visit, error)
	GetVisit(context.Context, string) (*Visit, error)
	ApplyVisitRouting(context.Context, Visit) error
	ListQueueEntries(context.Context, string) ([]QueueEntry, error)
	GetQueueEntry(context.Context, string) (*QueueEntry, error)
	StartEncounter(context.Context, string, Encounter, string, string) (*EncounterStart, error)
	CreateQueueEntry(context.Context, QueueEntry, *string, bool) (*QueueEntry, error)
	TransitionQueueEntry(context.Context, QueueEntry, string, string, *string, *string, bool) (*QueueEntry, error)
	ListQueueHistory(context.Context, string) ([]QueueHistory, error)
	ListRoutingRules(context.Context) ([]RoutingRule, error)
	CreateRoutingRule(context.Context, RoutingRule) (*RoutingRule, error)
	SearchConcepts(context.Context, string, int) ([]Concept, error)
	SearchICD11Concepts(context.Context, string, int) ([]Concept, error)
	ListDiagnosisConcepts(context.Context, DiagnosisFilters) ([]Concept, int, error)
	SetDiagnosisConceptEnabled(context.Context, string, bool) (*Concept, error)
	ResolveICD11Concept(context.Context, string, string) (*Concept, error)
	ListAllergens(context.Context) ([]Allergen, error)
	CreateAllergen(context.Context, Allergen) (*Allergen, error)
	UpdateAllergen(context.Context, string, UpdateAllergenRequest) (*Allergen, error)
	SetAllergenActive(context.Context, string, bool) (*Allergen, error)
	GetActiveAllergen(context.Context, string) (*Allergen, error)
	FindActiveOutpatientVisit(context.Context, string) (*Visit, error)
	ListVisits(context.Context, string, string) ([]Visit, error)
	ListOutpatientVisitItems(context.Context, OutpatientVisitFilters) ([]OutpatientVisitListItem, int, error)
	CreateEncounter(context.Context, Encounter) (*Encounter, error)
	CreateEncounterWithForm(context.Context, Encounter, string, string) (*Encounter, error)
	GetEncounter(context.Context, string) (*Encounter, error)
	ListEncounters(context.Context, string) ([]Encounter, error)
	CompleteEncounter(context.Context, string, string) (*Encounter, error)
	CreateObservations(context.Context, []Observation) ([]Observation, error)
	ListObservations(context.Context, string) ([]Observation, error)
	CreateNote(context.Context, ClinicalNote) (*ClinicalNote, error)
	ListNotes(context.Context, string) ([]ClinicalNote, error)
	CreateDiagnosis(context.Context, Diagnosis) (*Diagnosis, error)
	ListDiagnoses(context.Context, string) ([]Diagnosis, error)
	CreateAllergy(context.Context, Allergy) (*Allergy, error)
	ListAllergies(context.Context, string) ([]Allergy, error)
	CompleteVisit(context.Context, string) (*Visit, error)
	GetCurrentVisitQueueEntry(context.Context, string) (*QueueEntry, error)
	ApplyEventRouting(context.Context, string, string, string, string, string, string, *string) error
	CreateOrder(context.Context, ClinicalOrder) (*ClinicalOrder, error)
	GetOrder(context.Context, string) (*ClinicalOrder, error)
	ListOrders(context.Context, OrderFilters) ([]ClinicalOrder, int, error)
	TransitionOrder(context.Context, ClinicalOrder, string, string) (*ClinicalOrder, error)
	HasActiveMedicationAllergy(context.Context, string) (bool, error)
	HasUnresolvedReviewOrders(context.Context, string) (bool, error)
}
