package clinical

import (
	"github.com/go-chi/chi/v5"
	"nodus-health/internal/middleware"
)

func (h *Handler) RegisterRoutes(r chi.Router) {
	r.Group(func(r chi.Router) {
		r.Use(middleware.Authenticate(h.jwtSecret, h.authorizer))
		r.With(middleware.RequirePermission("templates:manage")).Get("/clinical/config/templates", h.ListTemplates)
		r.With(middleware.RequirePermission("templates:manage")).Post("/clinical/config/templates", h.CreateTemplate)
		r.With(middleware.RequirePermission("templates:manage")).Get("/clinical/config/templates/{templateId}", h.GetTemplate)
		r.With(middleware.RequirePermission("templates:manage")).Post("/clinical/config/templates/{templateId}/draft", h.CreateTemplateDraft)
		r.With(middleware.RequirePermission("templates:manage")).Put("/clinical/config/templates/{templateId}/draft", h.UpdateTemplateDraft)
		r.With(middleware.RequirePermission("templates:manage")).Post("/clinical/config/templates/{templateId}/publish", h.PublishTemplate)
		r.With(middleware.RequirePermission("templates:manage")).Post("/clinical/config/templates/{templateId}/default", h.SetDefaultTemplate)
		r.With(middleware.RequirePermission("templates:manage")).Post("/clinical/config/templates/{templateId}/archive", h.ArchiveTemplate)
		r.With(middleware.RequireAnyPermission("clinical:read", "catalogues:manage", "orders:place")).Get("/clinical/config/services", h.ListCatalogueServices)
		r.With(middleware.RequirePermission("catalogues:manage")).Post("/clinical/config/services", h.CreateCatalogueService)
		r.With(middleware.RequirePermission("catalogues:manage")).Patch("/clinical/config/services/{itemId}", h.UpdateCatalogueService)
		r.With(middleware.RequirePermission("catalogues:manage")).Post("/clinical/config/services/{itemId}/{action:deactivate|reactivate}", h.CatalogueServiceLifecycle)
		r.With(middleware.RequireAnyPermission("clinical:read", "catalogues:manage", "prescriptions:place")).Get("/clinical/config/medications", h.ListMedicationCatalogue)
		r.With(middleware.RequirePermission("catalogues:manage")).Post("/clinical/config/medications", h.CreateMedicationDefinition)
		r.With(middleware.RequirePermission("catalogues:manage")).Patch("/clinical/config/medications/{itemId}", h.UpdateMedicationDefinition)
		r.With(middleware.RequirePermission("catalogues:manage")).Post("/clinical/config/medications/{itemId}/{action:deactivate|reactivate}", h.MedicationLifecycle)
		r.With(middleware.RequirePermission("catalogues:manage")).Get("/clinical/config/reference/{catalogue:services|medications}", h.ListCatalogueReferences)
		r.With(middleware.RequirePermission("catalogues:manage")).Post("/clinical/config/services/adopt", h.AdoptServiceReferences)
		r.With(middleware.RequirePermission("catalogues:manage")).Post("/clinical/config/medications/adopt", h.AdoptMedicationReferences)
		r.With(middleware.RequirePermission("catalogues:manage")).Get("/clinical/config/{catalogue:services|medications}/imports/template", h.CatalogueImportTemplate)
		r.With(middleware.RequirePermission("catalogues:manage")).Post("/clinical/config/{catalogue:services|medications}/imports/preview", h.PreviewCatalogueImport)
		r.With(middleware.RequirePermission("catalogues:manage")).Post("/clinical/config/{catalogue:services|medications}/imports/{importId}/commit", h.CommitCatalogueImport)
		r.With(middleware.RequirePermission("facilities:manage")).Get("/clinical/config/diagnoses", h.ListDiagnosisConfiguration)
		r.With(middleware.RequirePermission("facilities:manage")).Patch("/clinical/config/diagnoses/{conceptId}", h.SetDiagnosisAvailability)
		r.With(middleware.RequireAnyPermission("clinical:read", "facilities:manage")).Get("/clinical/config/allergens", h.ListAllergenConfiguration)
		r.With(middleware.RequirePermission("facilities:manage")).Post("/clinical/config/allergens", h.CreateAllergenConfiguration)
		r.With(middleware.RequirePermission("facilities:manage")).Patch("/clinical/config/allergens/{allergenId}", h.UpdateAllergenConfiguration)
		r.With(middleware.RequirePermission("facilities:manage")).Post("/clinical/config/allergens/{allergenId}/{action:deactivate|reactivate}", h.AllergenLifecycle)
		r.With(middleware.RequirePermission("clinical:read")).Get("/clinical/config/{kind}", h.ListResources)
		r.With(middleware.RequirePermission("facilities:manage")).Post("/clinical/config/{kind}", h.CreateResource)
		r.With(middleware.RequirePermission("facilities:manage")).Patch("/clinical/config/{kind}/{resourceId}", h.UpdateResource)
		r.With(middleware.RequirePermission("facilities:manage")).Get("/clinical/config/{kind}/{resourceId}/deactivation-impact", h.DeactivationImpact)
		r.With(middleware.RequirePermission("facilities:manage")).Post("/clinical/config/{kind}/{resourceId}/deactivate", h.DeactivateResource)
		r.With(middleware.RequirePermission("facilities:manage")).Post("/clinical/config/{kind}/{resourceId}/reactivate", h.ReactivateResource)
		r.With(middleware.RequirePermission("clinical:write")).Post("/clinical/visits", h.CreateVisit)
		r.With(middleware.RequirePermission("outpatient:check-in")).Post("/clinical/outpatient/check-ins", h.OutpatientCheckIn)
		r.With(middleware.RequirePermission("outpatient:check-in"), middleware.RequirePermission("outpatient:duplicate-override")).Post("/clinical/outpatient/check-ins/override", h.OutpatientCheckInOverride)
		r.With(middleware.RequirePermission("outpatient:read")).Get("/clinical/outpatient/visits", h.ListOutpatientVisits)
		r.With(middleware.RequirePermission("outpatient:read")).Get("/clinical/visits/{visitId}", h.GetVisit)
		r.With(middleware.RequirePermission("outpatient:read")).Get("/clinical/visits/{visitId}/context", h.VisitContext)
		r.With(middleware.RequirePermission("outpatient:read")).Get("/clinical/visits/{visitId}/summary", h.VisitSummary)
		r.With(middleware.RequireAnyPermission("outpatient:triage", "outpatient:consult")).Post("/clinical/visits/{visitId}/encounters", h.CreateEncounter)
		r.With(middleware.RequirePermission("outpatient:consult"), middleware.RequirePermission("outpatient:workflow-override")).Post("/clinical/visits/{visitId}/encounters/override", h.CreateEncounterOverride)
		r.With(middleware.RequirePermission("outpatient:read")).Get("/clinical/visits/{visitId}/encounters", h.ListEncounters)
		r.With(middleware.RequirePermission("outpatient:triage")).Post("/clinical/encounters/{encounterId}/observations", h.RecordObservations)
		r.With(middleware.RequirePermission("outpatient:read")).Get("/clinical/encounters/{encounterId}/form", h.GetEncounterForm)
		r.With(middleware.RequireAnyPermission("outpatient:triage", "outpatient:consult")).Put("/clinical/encounters/{encounterId}/form", h.SaveEncounterForm)
		r.With(middleware.RequireAnyPermission("outpatient:triage", "outpatient:consult")).Post("/clinical/encounters/{encounterId}/form/submit", h.SubmitEncounterForm)
		r.With(middleware.RequireAnyPermission("outpatient:triage", "outpatient:consult")).Post("/clinical/encounters/{encounterId}/complete", h.CompleteEncounter)
		r.With(middleware.RequirePermission("outpatient:consult")).Post("/clinical/visits/{visitId}/notes", h.CreateNote)
		r.With(middleware.RequirePermission("outpatient:consult")).Post("/clinical/visits/{visitId}/diagnoses", h.CreateDiagnosis)
		r.With(middleware.RequireAnyPermission("outpatient:triage", "outpatient:consult")).Post("/clinical/patients/{patientId}/allergies", h.CreateAllergy)
		r.With(middleware.RequirePermission("outpatient:read")).Get("/clinical/patients/{patientId}/allergies", h.ListAllergies)
		r.With(middleware.RequirePermission("outpatient:complete")).Post("/clinical/visits/{visitId}/complete", h.CompleteVisit)
		r.With(middleware.RequirePermission("outpatient:complete"), middleware.RequirePermission("outpatient:workflow-override")).Post("/clinical/visits/{visitId}/complete/override", h.CompleteVisitOverride)
		r.With(middleware.RequirePermission("queues:view")).Get("/clinical/queues/{queueId}/entries", h.ListEntries)
		r.With(middleware.RequirePermission("queues:operate")).Post("/clinical/queues/{queueId}/entries", h.Enqueue)
		r.With(middleware.RequirePermission("queues:operate")).Post("/clinical/queue-entries/{entryId}/transition", h.Transition)
		r.With(middleware.RequirePermission("outpatient:triage")).Post("/clinical/queue-entries/{entryId}/start-triage", h.StartTriage)
		r.With(middleware.RequirePermission("outpatient:consult")).Post("/clinical/queue-entries/{entryId}/start-consultation", h.StartConsultation)
		r.With(middleware.RequirePermission("clinical:read")).Get("/clinical/queue-entries/{entryId}/history", h.History)
		r.With(middleware.RequirePermission("queues:configure")).Get("/clinical/routing-rules", h.ListRules)
		r.With(middleware.RequirePermission("queues:configure")).Post("/clinical/routing-rules", h.CreateRule)
		r.With(middleware.RequirePermission("orders:place")).Post("/clinical/visits/{visitId}/orders", h.CreateServiceOrder)
		r.With(middleware.RequirePermission("prescriptions:place")).Post("/clinical/visits/{visitId}/prescriptions", h.CreatePrescription)
		r.With(middleware.RequirePermission("orders:read")).Get("/clinical/visits/{visitId}/orders", h.ListVisitOrders)
		r.With(middleware.RequirePermission("orders:read")).Get("/clinical/orders", h.ListOrders)
		r.With(middleware.RequirePermission("orders:fulfill")).Post("/clinical/orders/{orderId}/transition", h.TransitionOrder)
		r.With(middleware.RequirePermission("orders:cancel")).Post("/clinical/orders/{orderId}/cancel", h.CancelOrder)
		r.With(middleware.RequirePermission("clinical:read")).Get("/clinical/terminology/icd10", h.ICD10)
		r.With(middleware.RequirePermission("clinical:read")).Get("/clinical/terminology/icd11", h.ICD11)
	})
}
