// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package sqlcgen

import (
	"context"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRolePermissionParams struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, name, description, is_superuser_role, requires_provider_identifier)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, is_superuser_role, requires_provider_identifier, created_at, updated_at, tenant_id
`

type CreateRoleParams struct {
	ID                         string `json:"id"`
	Name                       string `json:"name"`
	Description                string `json:"description"`
	IsSuperuserRole            bool   `json:"is_superuser_role"`
	RequiresProviderIdentifier bool   `json:"requires_provider_identifier"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsSuperuserRole,
		arg.RequiresProviderIdentifier,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSuperuserRole,
		&i.RequiresProviderIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getPermissionsByCodes = `-- name: GetPermissionsByCodes :many
SELECT id, code, description FROM permissions WHERE code = ANY($1::text[])
`

func (q *Queries) GetPermissionsByCodes(ctx context.Context, codes []string) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getPermissionsByCodes, codes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Code, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, description, is_superuser_role, requires_provider_identifier, created_at, updated_at, tenant_id FROM roles WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsSuperuserRole,
		&i.RequiresProviderIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getRolesByIDs = `-- name: GetRolesByIDs :many
SELECT id, name, description, is_superuser_role, requires_provider_identifier, created_at, updated_at, tenant_id FROM roles WHERE id::text = ANY($1::text[])
`

func (q *Queries) GetRolesByIDs(ctx context.Context, ids []string) ([]Role, error) {
	rows, err := q.db.Query(ctx, getRolesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsSuperuserRole,
			&i.RequiresProviderIdentifier,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasSuperuserRole = `-- name: HasSuperuserRole :one
SELECT EXISTS (
    SELECT 1 FROM user_roles ur
    JOIN roles r ON r.id = ur.role_id
    WHERE ur.user_id = $1 AND r.is_superuser_role = true
)
`

func (q *Queries) HasSuperuserRole(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasSuperuserRole, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listRolesWithPermissions = `-- name: ListRolesWithPermissions :many
SELECT r.id, r.tenant_id, r.name, r.description, r.is_superuser_role, r.requires_provider_identifier,
    COALESCE(array_agg(DISTINCT p.code) FILTER (WHERE p.code IS NOT NULL), '{}')::text[] AS permission_codes
FROM roles r
LEFT JOIN role_permissions rp ON rp.role_id = r.id
LEFT JOIN permissions p ON p.id = rp.permission_id
GROUP BY r.id
ORDER BY r.name
`

type ListRolesWithPermissionsRow struct {
	ID                         string   `json:"id"`
	TenantID                   string   `json:"tenant_id"`
	Name                       string   `json:"name"`
	Description                string   `json:"description"`
	IsSuperuserRole            bool     `json:"is_superuser_role"`
	RequiresProviderIdentifier bool     `json:"requires_provider_identifier"`
	PermissionCodes            []string `json:"permission_codes"`
}

func (q *Queries) ListRolesWithPermissions(ctx context.Context) ([]ListRolesWithPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listRolesWithPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesWithPermissionsRow
	for rows.Next() {
		var i ListRolesWithPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsSuperuserRole,
			&i.RequiresProviderIdentifier,
			&i.PermissionCodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
