// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patients.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIdentifiers = `-- name: CountIdentifiers :one
SELECT count(*) FROM patient_identifiers WHERE patient_id = $1
`

func (q *Queries) CountIdentifiers(ctx context.Context, patientID string) (int64, error) {
	row := q.db.QueryRow(ctx, countIdentifiers, patientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPatients = `-- name: CountPatients :one
SELECT count(*) FROM patients
WHERE tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
  AND ($1::text IS NULL OR
       full_name ILIKE '%' || $1::text || '%' OR
       mrn ILIKE '%' || $1::text || '%' OR
       national_id ILIKE '%' || $1::text || '%' OR
       phone ILIKE '%' || $1::text || '%')
  AND ($2::patient_status[] IS NULL OR status = ANY($2::patient_status[]))
  AND ($3::patient_gender[] IS NULL OR gender = ANY($3::patient_gender[]))
  AND ($4::boolean IS NULL OR insured = $4::boolean)
  AND ($5::date IS NULL OR created_at::date >= $5::date)
  AND ($6::date IS NULL OR created_at::date <= $6::date)
`

type CountPatientsParams struct {
	Q        *string         `json:"q"`
	Statuses []PatientStatus `json:"statuses"`
	Genders  []PatientGender `json:"genders"`
	Insured  *bool           `json:"insured"`
	RegFrom  pgtype.Date     `json:"reg_from"`
	RegTo    pgtype.Date     `json:"reg_to"`
}

func (q *Queries) CountPatients(ctx context.Context, arg CountPatientsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPatients,
		arg.Q,
		arg.Statuses,
		arg.Genders,
		arg.Insured,
		arg.RegFrom,
		arg.RegTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const decideCorrection = `-- name: DecideCorrection :exec
UPDATE patient_corrections SET status = $2::patient_correction_status, decided_by = $3::uuid, decided_at = $4, decision_note = $5
WHERE id = $1
`

type DecideCorrectionParams struct {
	ID           string                  `json:"id"`
	Column2      PatientCorrectionStatus `json:"column_2"`
	Column3      string                  `json:"column_3"`
	DecidedAt    pgtype.Timestamptz      `json:"decided_at"`
	DecisionNote *string                 `json:"decision_note"`
}

func (q *Queries) DecideCorrection(ctx context.Context, arg DecideCorrectionParams) error {
	_, err := q.db.Exec(ctx, decideCorrection,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.DecidedAt,
		arg.DecisionNote,
	)
	return err
}

const deleteIdentifier = `-- name: DeleteIdentifier :exec
DELETE FROM patient_identifiers WHERE id = $1 AND patient_id = $2
`

type DeleteIdentifierParams struct {
	ID        string `json:"id"`
	PatientID string `json:"patient_id"`
}

func (q *Queries) DeleteIdentifier(ctx context.Context, arg DeleteIdentifierParams) error {
	_, err := q.db.Exec(ctx, deleteIdentifier, arg.ID, arg.PatientID)
	return err
}

const findDuplicateCandidates = `-- name: FindDuplicateCandidates :many
SELECT p.id, p.tenant_id, p.mrn, p.full_name, p.dob, p.dob_estimated, p.approx_age_years, p.gender, p.phone, p.address, p.national_id, p.status, p.date_of_death, p.insured, p.guardian_id, p.merged_into_id, p.created_at, p.updated_at,
  similarity(p.full_name, $1::text) AS name_score,
  ($2::date IS NOT NULL AND p.dob = $2::date) AS dob_exact,
  ($3::text IS NOT NULL AND p.national_id = $3::text) AS national_id_exact,
  ($4::text IS NOT NULL AND p.phone = $4::text) AS phone_exact
FROM patients p
WHERE p.tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
  AND p.status != 'merged'
  AND (p.full_name % $1::text
       OR ($3::text IS NOT NULL AND p.national_id = $3::text)
       OR ($4::text IS NOT NULL AND p.phone = $4::text))
ORDER BY (similarity(p.full_name, $1::text)
  + (CASE WHEN $2::date IS NOT NULL AND p.dob = $2::date THEN 0.4 ELSE 0 END)
  + (CASE WHEN $3::text IS NOT NULL AND p.national_id = $3::text THEN 0.5 ELSE 0 END)
  + (CASE WHEN $4::text IS NOT NULL AND p.phone = $4::text THEN 0.2 ELSE 0 END)) DESC
LIMIT 10
`

type FindDuplicateCandidatesParams struct {
	FullName   string      `json:"full_name"`
	Dob        pgtype.Date `json:"dob"`
	NationalID *string     `json:"national_id"`
	Phone      *string     `json:"phone"`
}

type FindDuplicateCandidatesRow struct {
	ID              string             `json:"id"`
	TenantID        string             `json:"tenant_id"`
	Mrn             string             `json:"mrn"`
	FullName        string             `json:"full_name"`
	Dob             pgtype.Date        `json:"dob"`
	DobEstimated    bool               `json:"dob_estimated"`
	ApproxAgeYears  *int16             `json:"approx_age_years"`
	Gender          PatientGender      `json:"gender"`
	Phone           *string            `json:"phone"`
	Address         *string            `json:"address"`
	NationalID      *string            `json:"national_id"`
	Status          PatientStatus      `json:"status"`
	DateOfDeath     pgtype.Timestamptz `json:"date_of_death"`
	Insured         bool               `json:"insured"`
	GuardianID      *string            `json:"guardian_id"`
	MergedIntoID    *string            `json:"merged_into_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	NameScore       float32            `json:"name_score"`
	DobExact        *bool              `json:"dob_exact"`
	NationalIDExact *bool              `json:"national_id_exact"`
	PhoneExact      *bool              `json:"phone_exact"`
}

// FindDuplicateCandidates ranks existing (non-merged) patients in the
// tenant by a combined trigram-name-similarity + exact-field score:
func (q *Queries) FindDuplicateCandidates(ctx context.Context, arg FindDuplicateCandidatesParams) ([]FindDuplicateCandidatesRow, error) {
	rows, err := q.db.Query(ctx, findDuplicateCandidates,
		arg.FullName,
		arg.Dob,
		arg.NationalID,
		arg.Phone,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindDuplicateCandidatesRow
	for rows.Next() {
		var i FindDuplicateCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Mrn,
			&i.FullName,
			&i.Dob,
			&i.DobEstimated,
			&i.ApproxAgeYears,
			&i.Gender,
			&i.Phone,
			&i.Address,
			&i.NationalID,
			&i.Status,
			&i.DateOfDeath,
			&i.Insured,
			&i.GuardianID,
			&i.MergedIntoID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NameScore,
			&i.DobExact,
			&i.NationalIDExact,
			&i.PhoneExact,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCorrectionByID = `-- name: GetCorrectionByID :one
SELECT id, tenant_id, patient_id, field, current_value, requested_value, evidence_note, status, submitted_by, decided_by, decided_at, decision_note, created_at, updated_at FROM patient_corrections WHERE id = $1
`

func (q *Queries) GetCorrectionByID(ctx context.Context, id string) (PatientCorrection, error) {
	row := q.db.QueryRow(ctx, getCorrectionByID, id)
	var i PatientCorrection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PatientID,
		&i.Field,
		&i.CurrentValue,
		&i.RequestedValue,
		&i.EvidenceNote,
		&i.Status,
		&i.SubmittedBy,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT id, tenant_id, mrn, full_name, dob, dob_estimated, approx_age_years, gender, phone, address, national_id, status, date_of_death, insured, guardian_id, merged_into_id, created_at, updated_at FROM patients
WHERE id = $1 AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
`

func (q *Queries) GetPatientByID(ctx context.Context, id string) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByID, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Mrn,
		&i.FullName,
		&i.Dob,
		&i.DobEstimated,
		&i.ApproxAgeYears,
		&i.Gender,
		&i.Phone,
		&i.Address,
		&i.NationalID,
		&i.Status,
		&i.DateOfDeath,
		&i.Insured,
		&i.GuardianID,
		&i.MergedIntoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertActivity = `-- name: InsertActivity :exec
INSERT INTO patient_activity_log (id, patient_id, user_id, kind, text)
VALUES ($1, $2, $3, $4, $5)
`

type InsertActivityParams struct {
	ID        string  `json:"id"`
	PatientID string  `json:"patient_id"`
	UserID    *string `json:"user_id"`
	Kind      string  `json:"kind"`
	Text      string  `json:"text"`
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.Exec(ctx, insertActivity,
		arg.ID,
		arg.PatientID,
		arg.UserID,
		arg.Kind,
		arg.Text,
	)
	return err
}

const insertCorrection = `-- name: InsertCorrection :exec
INSERT INTO patient_corrections (id, patient_id, field, current_value, requested_value, evidence_note, submitted_by)
VALUES ($1, $2, $3, $4, $5, $6, $7::uuid)
`

type InsertCorrectionParams struct {
	ID             string  `json:"id"`
	PatientID      string  `json:"patient_id"`
	Field          string  `json:"field"`
	CurrentValue   *string `json:"current_value"`
	RequestedValue string  `json:"requested_value"`
	EvidenceNote   *string `json:"evidence_note"`
	SubmittedBy    *string `json:"submitted_by"`
}

func (q *Queries) InsertCorrection(ctx context.Context, arg InsertCorrectionParams) error {
	_, err := q.db.Exec(ctx, insertCorrection,
		arg.ID,
		arg.PatientID,
		arg.Field,
		arg.CurrentValue,
		arg.RequestedValue,
		arg.EvidenceNote,
		arg.SubmittedBy,
	)
	return err
}

const insertIdentifier = `-- name: InsertIdentifier :exec
INSERT INTO patient_identifiers (id, patient_id, id_type, id_value)
VALUES ($1, $2, $3, $4)
`

type InsertIdentifierParams struct {
	ID        string `json:"id"`
	PatientID string `json:"patient_id"`
	IDType    string `json:"id_type"`
	IDValue   string `json:"id_value"`
}

func (q *Queries) InsertIdentifier(ctx context.Context, arg InsertIdentifierParams) error {
	_, err := q.db.Exec(ctx, insertIdentifier,
		arg.ID,
		arg.PatientID,
		arg.IDType,
		arg.IDValue,
	)
	return err
}

const insertPatient = `-- name: InsertPatient :exec
INSERT INTO patients (
  id, tenant_id, mrn, full_name, dob, dob_estimated, approx_age_years, gender,
  phone, address, national_id, status, insured, guardian_id
) VALUES (
  $1, NULLIF(current_setting('app.tenant_id', true), '')::uuid, $2, $3,
  $4::date, $5, $6::smallint, $7::patient_gender,
  $8, $9, $10, 'active', $11, $12::uuid
)
`

type InsertPatientParams struct {
	ID             string        `json:"id"`
	Mrn            string        `json:"mrn"`
	FullName       string        `json:"full_name"`
	Dob            pgtype.Date   `json:"dob"`
	DobEstimated   bool          `json:"dob_estimated"`
	ApproxAgeYears *int16        `json:"approx_age_years"`
	Gender         PatientGender `json:"gender"`
	Phone          *string       `json:"phone"`
	Address        *string       `json:"address"`
	NationalID     *string       `json:"national_id"`
	Insured        bool          `json:"insured"`
	GuardianID     *string       `json:"guardian_id"`
}

func (q *Queries) InsertPatient(ctx context.Context, arg InsertPatientParams) error {
	_, err := q.db.Exec(ctx, insertPatient,
		arg.ID,
		arg.Mrn,
		arg.FullName,
		arg.Dob,
		arg.DobEstimated,
		arg.ApproxAgeYears,
		arg.Gender,
		arg.Phone,
		arg.Address,
		arg.NationalID,
		arg.Insured,
		arg.GuardianID,
	)
	return err
}

const issuePatientMRNNumber = `-- name: IssuePatientMRNNumber :one
INSERT INTO patient_mrn_sequences (tenant_id, next_value)
VALUES (NULLIF(current_setting('app.tenant_id', true), '')::uuid, 2)
ON CONFLICT (tenant_id) DO UPDATE SET next_value = patient_mrn_sequences.next_value + 1
RETURNING next_value - 1 AS issued
`

// IssuePatientMRNNumber atomically issues the next sequential MRN number
// for the current tenant. First call for a tenant inserts the counter row
// (seeded so the *next* value is 2) and returns 1; every call after that
// increments and returns the pre-increment value - so numbers issued are
// 1, 2, 3, ... per tenant, with no separate provisioning step required.
func (q *Queries) IssuePatientMRNNumber(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, issuePatientMRNNumber)
	var issued int32
	err := row.Scan(&issued)
	return issued, err
}

const listActivity = `-- name: ListActivity :many
SELECT id, tenant_id, patient_id, user_id, kind, text, created_at FROM patient_activity_log WHERE patient_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListActivity(ctx context.Context, patientID string) ([]PatientActivityLog, error) {
	rows, err := q.db.Query(ctx, listActivity, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientActivityLog
	for rows.Next() {
		var i PatientActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PatientID,
			&i.UserID,
			&i.Kind,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsents = `-- name: ListConsents :many
SELECT id, tenant_id, patient_id, scope, granted, granted_at, revoked_at, created_at, updated_at FROM patient_consents WHERE patient_id = $1 ORDER BY scope
`

func (q *Queries) ListConsents(ctx context.Context, patientID string) ([]PatientConsent, error) {
	rows, err := q.db.Query(ctx, listConsents, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientConsent
	for rows.Next() {
		var i PatientConsent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PatientID,
			&i.Scope,
			&i.Granted,
			&i.GrantedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCorrections = `-- name: ListCorrections :many
SELECT id, tenant_id, patient_id, field, current_value, requested_value, evidence_note, status, submitted_by, decided_by, decided_at, decision_note, created_at, updated_at FROM patient_corrections WHERE patient_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCorrections(ctx context.Context, patientID string) ([]PatientCorrection, error) {
	rows, err := q.db.Query(ctx, listCorrections, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientCorrection
	for rows.Next() {
		var i PatientCorrection
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PatientID,
			&i.Field,
			&i.CurrentValue,
			&i.RequestedValue,
			&i.EvidenceNote,
			&i.Status,
			&i.SubmittedBy,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecisionNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentifiers = `-- name: ListIdentifiers :many
SELECT id, tenant_id, patient_id, id_type, id_value, verified_at, created_at FROM patient_identifiers WHERE patient_id = $1 ORDER BY created_at
`

func (q *Queries) ListIdentifiers(ctx context.Context, patientID string) ([]PatientIdentifier, error) {
	rows, err := q.db.Query(ctx, listIdentifiers, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientIdentifier
	for rows.Next() {
		var i PatientIdentifier
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PatientID,
			&i.IDType,
			&i.IDValue,
			&i.VerifiedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatients = `-- name: ListPatients :many
SELECT id, tenant_id, mrn, full_name, dob, dob_estimated, approx_age_years, gender, phone, address, national_id, status, date_of_death, insured, guardian_id, merged_into_id, created_at, updated_at FROM patients
WHERE tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
  AND ($1::text IS NULL OR
       full_name ILIKE '%' || $1::text || '%' OR
       mrn ILIKE '%' || $1::text || '%' OR
       national_id ILIKE '%' || $1::text || '%' OR
       phone ILIKE '%' || $1::text || '%')
  AND ($2::patient_status[] IS NULL OR status = ANY($2::patient_status[]))
  AND ($3::patient_gender[] IS NULL OR gender = ANY($3::patient_gender[]))
  AND ($4::boolean IS NULL OR insured = $4::boolean)
  AND ($5::date IS NULL OR created_at::date >= $5::date)
  AND ($6::date IS NULL OR created_at::date <= $6::date)
ORDER BY created_at DESC
LIMIT $8 OFFSET $7
`

type ListPatientsParams struct {
	Q         *string         `json:"q"`
	Statuses  []PatientStatus `json:"statuses"`
	Genders   []PatientGender `json:"genders"`
	Insured   *bool           `json:"insured"`
	RegFrom   pgtype.Date     `json:"reg_from"`
	RegTo     pgtype.Date     `json:"reg_to"`
	OffsetVal int32           `json:"offset_val"`
	LimitVal  int32           `json:"limit_val"`
}

func (q *Queries) ListPatients(ctx context.Context, arg ListPatientsParams) ([]Patient, error) {
	rows, err := q.db.Query(ctx, listPatients,
		arg.Q,
		arg.Statuses,
		arg.Genders,
		arg.Insured,
		arg.RegFrom,
		arg.RegTo,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patient
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Mrn,
			&i.FullName,
			&i.Dob,
			&i.DobEstimated,
			&i.ApproxAgeYears,
			&i.Gender,
			&i.Phone,
			&i.Address,
			&i.NationalID,
			&i.Status,
			&i.DateOfDeath,
			&i.Insured,
			&i.GuardianID,
			&i.MergedIntoID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPatientDeceased = `-- name: MarkPatientDeceased :exec
UPDATE patients SET status = 'deceased', date_of_death = $2
WHERE id = $1 AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
`

type MarkPatientDeceasedParams struct {
	ID          string             `json:"id"`
	DateOfDeath pgtype.Timestamptz `json:"date_of_death"`
}

func (q *Queries) MarkPatientDeceased(ctx context.Context, arg MarkPatientDeceasedParams) error {
	_, err := q.db.Exec(ctx, markPatientDeceased, arg.ID, arg.DateOfDeath)
	return err
}

const reassignActivity = `-- name: ReassignActivity :exec
UPDATE patient_activity_log SET patient_id = $2 WHERE patient_id = $1
`

type ReassignActivityParams struct {
	PatientID   string `json:"patient_id"`
	PatientID_2 string `json:"patient_id_2"`
}

func (q *Queries) ReassignActivity(ctx context.Context, arg ReassignActivityParams) error {
	_, err := q.db.Exec(ctx, reassignActivity, arg.PatientID, arg.PatientID_2)
	return err
}

const reassignConsents = `-- name: ReassignConsents :exec
UPDATE patient_consents pc SET patient_id = $2
WHERE pc.patient_id = $1
  AND pc.scope NOT IN (SELECT scope FROM patient_consents WHERE patient_id = $2)
`

type ReassignConsentsParams struct {
	PatientID   string `json:"patient_id"`
	PatientID_2 string `json:"patient_id_2"`
}

// Consents carry a UNIQUE(patient_id, scope) constraint, so any away-side
// scope the keep side already has is left attached to the (now-merged,
// never-deleted) away record rather than conflicting.
func (q *Queries) ReassignConsents(ctx context.Context, arg ReassignConsentsParams) error {
	_, err := q.db.Exec(ctx, reassignConsents, arg.PatientID, arg.PatientID_2)
	return err
}

const reassignCorrections = `-- name: ReassignCorrections :exec
UPDATE patient_corrections SET patient_id = $2 WHERE patient_id = $1
`

type ReassignCorrectionsParams struct {
	PatientID   string `json:"patient_id"`
	PatientID_2 string `json:"patient_id_2"`
}

func (q *Queries) ReassignCorrections(ctx context.Context, arg ReassignCorrectionsParams) error {
	_, err := q.db.Exec(ctx, reassignCorrections, arg.PatientID, arg.PatientID_2)
	return err
}

const reassignIdentifiers = `-- name: ReassignIdentifiers :exec
UPDATE patient_identifiers SET patient_id = $2 WHERE patient_id = $1
`

type ReassignIdentifiersParams struct {
	PatientID   string `json:"patient_id"`
	PatientID_2 string `json:"patient_id_2"`
}

func (q *Queries) ReassignIdentifiers(ctx context.Context, arg ReassignIdentifiersParams) error {
	_, err := q.db.Exec(ctx, reassignIdentifiers, arg.PatientID, arg.PatientID_2)
	return err
}

const setPatientMergedInto = `-- name: SetPatientMergedInto :exec
UPDATE patients SET status = 'merged', merged_into_id = $2
WHERE id = $1 AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
`

type SetPatientMergedIntoParams struct {
	ID           string  `json:"id"`
	MergedIntoID *string `json:"merged_into_id"`
}

func (q *Queries) SetPatientMergedInto(ctx context.Context, arg SetPatientMergedIntoParams) error {
	_, err := q.db.Exec(ctx, setPatientMergedInto, arg.ID, arg.MergedIntoID)
	return err
}

const updatePatientContact = `-- name: UpdatePatientContact :exec
UPDATE patients SET phone = $2, address = $3
WHERE id = $1 AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
`

type UpdatePatientContactParams struct {
	ID      string  `json:"id"`
	Phone   *string `json:"phone"`
	Address *string `json:"address"`
}

func (q *Queries) UpdatePatientContact(ctx context.Context, arg UpdatePatientContactParams) error {
	_, err := q.db.Exec(ctx, updatePatientContact, arg.ID, arg.Phone, arg.Address)
	return err
}

const updatePatientDOB = `-- name: UpdatePatientDOB :exec
UPDATE patients SET dob = $2::date
WHERE id = $1 AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
`

type UpdatePatientDOBParams struct {
	ID      string      `json:"id"`
	Column2 pgtype.Date `json:"column_2"`
}

func (q *Queries) UpdatePatientDOB(ctx context.Context, arg UpdatePatientDOBParams) error {
	_, err := q.db.Exec(ctx, updatePatientDOB, arg.ID, arg.Column2)
	return err
}

const updatePatientFullName = `-- name: UpdatePatientFullName :exec
UPDATE patients SET full_name = $2
WHERE id = $1 AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
`

type UpdatePatientFullNameParams struct {
	ID       string `json:"id"`
	FullName string `json:"full_name"`
}

func (q *Queries) UpdatePatientFullName(ctx context.Context, arg UpdatePatientFullNameParams) error {
	_, err := q.db.Exec(ctx, updatePatientFullName, arg.ID, arg.FullName)
	return err
}

const updatePatientGender = `-- name: UpdatePatientGender :exec
UPDATE patients SET gender = $2::patient_gender
WHERE id = $1 AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
`

type UpdatePatientGenderParams struct {
	ID      string        `json:"id"`
	Column2 PatientGender `json:"column_2"`
}

func (q *Queries) UpdatePatientGender(ctx context.Context, arg UpdatePatientGenderParams) error {
	_, err := q.db.Exec(ctx, updatePatientGender, arg.ID, arg.Column2)
	return err
}

const updatePatientNationalID = `-- name: UpdatePatientNationalID :exec
UPDATE patients SET national_id = $2
WHERE id = $1 AND tenant_id = NULLIF(current_setting('app.tenant_id', true), '')::uuid
`

type UpdatePatientNationalIDParams struct {
	ID         string  `json:"id"`
	NationalID *string `json:"national_id"`
}

func (q *Queries) UpdatePatientNationalID(ctx context.Context, arg UpdatePatientNationalIDParams) error {
	_, err := q.db.Exec(ctx, updatePatientNationalID, arg.ID, arg.NationalID)
	return err
}

const upsertConsent = `-- name: UpsertConsent :one
INSERT INTO patient_consents (id, patient_id, scope, granted, granted_at, revoked_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (patient_id, scope) DO UPDATE SET granted = EXCLUDED.granted, granted_at = EXCLUDED.granted_at, revoked_at = EXCLUDED.revoked_at
RETURNING id, tenant_id, patient_id, scope, granted, granted_at, revoked_at, created_at, updated_at
`

type UpsertConsentParams struct {
	ID        string             `json:"id"`
	PatientID string             `json:"patient_id"`
	Scope     string             `json:"scope"`
	Granted   bool               `json:"granted"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) UpsertConsent(ctx context.Context, arg UpsertConsentParams) (PatientConsent, error) {
	row := q.db.QueryRow(ctx, upsertConsent,
		arg.ID,
		arg.PatientID,
		arg.Scope,
		arg.Granted,
		arg.GrantedAt,
		arg.RevokedAt,
	)
	var i PatientConsent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PatientID,
		&i.Scope,
		&i.Granted,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
