// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (id, "timestamp", user_id, action, target_resource, ip_address, result, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	ID             string             `json:"id"`
	Timestamp      pgtype.Timestamptz `json:"timestamp"`
	UserID         *string            `json:"user_id"`
	Action         string             `json:"action"`
	TargetResource string             `json:"target_resource"`
	IpAddress      string             `json:"ip_address"`
	Result         AuditResult        `json:"result"`
	Metadata       []byte             `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.Timestamp,
		arg.UserID,
		arg.Action,
		arg.TargetResource,
		arg.IpAddress,
		arg.Result,
		arg.Metadata,
	)
	return err
}
