// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditResult string

const (
	AuditResultSuccess AuditResult = "success"
	AuditResultFailure AuditResult = "failure"
)

func (e *AuditResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditResult(s)
	case string:
		*e = AuditResult(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditResult: %T", src)
	}
	return nil
}

type NullAuditResult struct {
	AuditResult AuditResult `json:"audit_result"`
	Valid       bool        `json:"valid"` // Valid is true if AuditResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditResult) Scan(value interface{}) error {
	if value == nil {
		ns.AuditResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditResult), nil
}

type MfaFactorType string

const (
	MfaFactorTypeTotp      MfaFactorType = "totp"
	MfaFactorTypeBiometric MfaFactorType = "biometric"
)

func (e *MfaFactorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MfaFactorType(s)
	case string:
		*e = MfaFactorType(s)
	default:
		return fmt.Errorf("unsupported scan type for MfaFactorType: %T", src)
	}
	return nil
}

type NullMfaFactorType struct {
	MfaFactorType MfaFactorType `json:"mfa_factor_type"`
	Valid         bool          `json:"valid"` // Valid is true if MfaFactorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMfaFactorType) Scan(value interface{}) error {
	if value == nil {
		ns.MfaFactorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MfaFactorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMfaFactorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MfaFactorType), nil
}

type OrganizationStatus string

const (
	OrganizationStatusPending   OrganizationStatus = "pending"
	OrganizationStatusActive    OrganizationStatus = "active"
	OrganizationStatusSuspended OrganizationStatus = "suspended"
)

func (e *OrganizationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrganizationStatus(s)
	case string:
		*e = OrganizationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrganizationStatus: %T", src)
	}
	return nil
}

type NullOrganizationStatus struct {
	OrganizationStatus OrganizationStatus `json:"organization_status"`
	Valid              bool               `json:"valid"` // Valid is true if OrganizationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrganizationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrganizationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrganizationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrganizationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrganizationStatus), nil
}

type UserStatus string

const (
	UserStatusInvited       UserStatus = "invited"
	UserStatusActive        UserStatus = "active"
	UserStatusSuspended     UserStatus = "suspended"
	UserStatusPendingReview UserStatus = "pending_review"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AuditLog struct {
	ID             string             `json:"id"`
	Timestamp      pgtype.Timestamptz `json:"timestamp"`
	UserID         *string            `json:"user_id"`
	Action         string             `json:"action"`
	TargetResource string             `json:"target_resource"`
	IpAddress      string             `json:"ip_address"`
	Result         AuditResult        `json:"result"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	TenantID       string             `json:"tenant_id"`
}

type EnrollmentToken struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TenantID   string             `json:"tenant_id"`
}

type Invitation struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	InvitedBy string             `json:"invited_by"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TenantID  string             `json:"tenant_id"`
}

type LoginChallenge struct {
	ID                 string             `json:"id"`
	UserID             string             `json:"user_id"`
	ChallengeTokenHash string             `json:"challenge_token_hash"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt         pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	TenantID           string             `json:"tenant_id"`
}

type MfaBackupCode struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TenantID  string             `json:"tenant_id"`
}

type MfaFactor struct {
	ID              string             `json:"id"`
	UserID          string             `json:"user_id"`
	Type            MfaFactorType      `json:"type"`
	Label           string             `json:"label"`
	SecretEncrypted *string            `json:"secret_encrypted"`
	PublicKey       *string            `json:"public_key"`
	ConfirmedAt     pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	TenantID        string             `json:"tenant_id"`
}

type Organization struct {
	ID               string             `json:"id"`
	OrganizationName string             `json:"organization_name"`
	Slug             string             `json:"slug"`
	Status           OrganizationStatus `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationActivationToken struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PasswordResetAttempt struct {
	ID                string             `json:"id"`
	UsernameAttempted string             `json:"username_attempted"`
	IpAddress         string             `json:"ip_address"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	TenantID          string             `json:"tenant_id"`
}

type PasswordResetToken struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TenantID  string             `json:"tenant_id"`
}

type Permission struct {
	ID          string `json:"id"`
	Code        string `json:"code"`
	Description string `json:"description"`
}

type RefreshToken struct {
	ID        string             `json:"id"`
	SessionID string             `json:"session_id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TenantID  string             `json:"tenant_id"`
}

type Role struct {
	ID                         string             `json:"id"`
	Name                       string             `json:"name"`
	Description                string             `json:"description"`
	IsSuperuserRole            bool               `json:"is_superuser_role"`
	RequiresProviderIdentifier bool               `json:"requires_provider_identifier"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	TenantID                   string             `json:"tenant_id"`
}

type RolePermission struct {
	RoleID       string `json:"role_id"`
	PermissionID string `json:"permission_id"`
	TenantID     string `json:"tenant_id"`
}

type Session struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	DeviceLabel  string             `json:"device_label"`
	IpAddress    string             `json:"ip_address"`
	UserAgent    string             `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	TenantID     string             `json:"tenant_id"`
}

type User struct {
	ID                  string             `json:"id"`
	FullName            string             `json:"full_name"`
	Username            string             `json:"username"`
	Email               string             `json:"email"`
	PasswordHash        *string            `json:"password_hash"`
	ProviderIdentifier  *string            `json:"provider_identifier"`
	Status              UserStatus         `json:"status"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
	PasswordChangedAt   pgtype.Timestamptz `json:"password_changed_at"`
	LastAccessReviewAt  pgtype.Timestamptz `json:"last_access_review_at"`
	NextAccessReviewDue pgtype.Timestamptz `json:"next_access_review_due"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TenantID            string             `json:"tenant_id"`
}

type UserRole struct {
	UserID     string             `json:"user_id"`
	RoleID     string             `json:"role_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	TenantID   string             `json:"tenant_id"`
}
